// Generated by https://pagedraw.io/pages/12008
import React from 'react';
import './border.css';


export default class Border extends React.Component {
  render() {
    return (
      <div className="border-border-8">
          <div className="border-0">
              <div className="border-rectangle_8">
                  <div className="border-0-0-0">
                      <div className="border-textplaceholder-2">
                          this.props.placeholder_override
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
