// Generated by https://pagedraw.io/pages/12008
import React from 'react';
import './centraltabgroup.css';


export default class Centraltabgroup extends React.Component {
  render() {
    return (
      <div className="centraltabgroup">
          { (this.props.state === "1") ?
              <div className="centraltabgroup-1-3">
                  <div className="centraltabgroup-0-0-0">
                      <div className="centraltabgroup-titletext-2">
                          <br/>
                          <div>Scorchable Payments Overview</div>
                          <br/>
                          <br/>
                      </div>
                  </div>
                  <div className="centraltabgroup-0-0-1">
                      <div className="centraltabgroup-summarytext-9">
                          <div>{"Scorchable payments are a simple way of making payments in dai or ether with improved safety over direct transfers for both the payer and payee using Ethereum. There are no fees involved nor any centralised third party controlling escrows. The risks of direct transfers are reduced by removing the ability to profit from fraud for both parties, so there is no incentive for scammers to ever participate. The process follows the following stages:"}</div>
                          <br/>
                          <br/>
                      </div>
                  </div>
                  <div className="centraltabgroup-0-0-2">
                      <div className="centraltabgroup-phasestext-2">
                          <div>Phase 1 - A payer creates a payment by sending the dai or ether into the contract, specifying the payee address, payee bond quantity required and the timeout period the payer must act by. After this stage the payer can withdraw their funds and cancel the payment.</div>
                          <br/>
                          <br/>
                          <div>Phase 2 - If a bond was specified the payer pays the bond, other wise this step is skipped. Once the bond is paid the payer can not reclaim the payment.</div>
                          <br/>
                          <br/>
                          <div>{"Phase 3 - After the payee optionally provides the good or service, the payer can either release the funds (including the payees bond) to the payee, or scorch them. Either action can be taken on any fraction of the funds. The payee may release the funds back to the payer in case they can not fulfil the deal. If the payer fails to act before the timeout date, or extend the timeout date, the payee may claim the funds."}</div>
                          <br/>
                          <br/>
                      </div>
                  </div>
                  <div className="centraltabgroup-0-0-3">
                      <div className="centraltabgroup-contract_address_0">
                          <div>Contract address 0x000</div>
                          <div>{"https://github.com/stobiewan/scorchable-payments"}</div>
                          <div>{"https://en.wikipedia.org/wiki/Scorched_earth"}</div>
                      </div>
                  </div>
              </div>
          : null}
          { (this.props.state === "2") ?
              <div className="centraltabgroup-2-0">
                  <div className="centraltabgroup-1-0-0">
                      <div className="centraltabgroup-send_-1">SEND</div>
                  </div>
              </div>
          : null}
          { (this.props.state === "3") ?
              <div className="centraltabgroup-3">
                  <div className="centraltabgroup-2-0-0">
                      <div className="centraltabgroup-receive_-6">RECEIVE</div>
                  </div>
              </div>
          : null}
      </div>
    );
  }
};
