// Generated by https://pagedraw.io/pages/12008
import React from 'react';
import './leftbutton.css';


export default class Leftbutton extends React.Component {
  render() {
    return (
      <div onClick={this.props.onClick} className="leftbutton-leftbutton-8">
          <div className="leftbutton-0">
              <div className="leftbutton-leftbuttonbackground-9">
                  <div className="leftbutton-0-0-0">
                      <div className="leftbutton-lefttext-2">{"<"}</div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
