// Generated by https://pagedraw.io/pages/12008
import React from 'react';
import './radiobutton.css';


export default class Radiobutton extends React.Component {
  render() {
    return (
      <div className="radiobutton">
          { ((this.props.state === 'selected' ? 'selected' : 'unselected') === "selected") ?
              <div className="radiobutton-selected-2">
                  <div className="radiobutton-0-0-0">
                      <div className="radiobutton-oval-6">
                          <div className="radiobutton-0-0-0-0-0">
                              <div className="radiobutton-oval_2" /> 
                          </div>
                      </div>
                  </div>
              </div>
          : null}
          { ((this.props.state === 'selected' ? 'selected' : 'unselected') === "unselected") ?
              <div className="radiobutton-unselected-8">
                  <div className="radiobutton-1-0-0">
                      <div onClick={() => this.props.onClick(this.props.id, this.props.name)} className="radiobutton-oval-1" /> 
                  </div>
              </div>
          : null}
      </div>
    );
  }
};
