// Generated by https://pagedraw.io/pages/12008
import React from 'react';
import './rightbutton.css';


export default class Rightbutton extends React.Component {
  render() {
    return (
      <div onClick={this.props.onClick} className="rightbutton-rightbutton-3">
          <div className="rightbutton-0">
              <div className="rightbutton-rightbuttonbackground-7">
                  <div className="rightbutton-0-0-0">
                      <div className="rightbutton-lefttext-5">{">"}</div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
