// Generated by https://pagedraw.io/pages/12008
import React from 'react';
import './textentrycomponent.css';


export default class Textentrycomponent extends React.Component {
  render() {
    return (
      <div className="textentrycomponent-textentrycomponent-2">
          <div className="textentrycomponent-0">
              <div className="textentrycomponent-textentry-2">
                  <div className="textentrycomponent-0-0-0">
                      <input type="text" placeholder="0x0000000000000000000000000000000000000000" value={this.props.value} onChange={this.props.onChange} className="textentrycomponent-text_input-1" /> 
                  </div>
              </div>
              <div className="textentrycomponent-description-1">
                  <div className="textentrycomponent-0-1-0">
                      <div className="textentrycomponent-description_-2">
                          {"Description:"}
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
