// Generated by https://pagedraw.io/pages/12008
import React from 'react';
import './textentrywithbutton.css';


export default class Textentrywithbutton extends React.Component {
  render() {
    return (
      <div className="textentrywithbutton-textentrywithbutton-5">
          <div className="textentrywithbutton-0">
              <div className="textentrywithbutton-textentry-3">
                  <div className="textentrywithbutton-0-0-0">
                      <input type="text" placeholder="0x0000000000000000000000000000000000000000" value={this.props.value} onChange={this.props.onChange} className="textentrywithbutton-text_input-8" /> 
                  </div>
              </div>
              <div className="textentrywithbutton-0-1">
                  <div className="textentrywithbutton-0-1-0">
                      <div className="textentrywithbutton-0-1-0-0">
                          <div className="textentrywithbutton-description-5" /> 
                          <div className="textentrywithbutton-description_-5">
                              { this.props.text2 }
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
